Update for PHP 8
beyondcode/helo-laravel pull request #25
Opened 2020-12-16 02:39 UTC by repat

See #24

2020-12-18 04:28 UTC, repat commented
![image](https://user-images.githubusercontent.com/516807/102574709-5391f780-4156-11eb-8197-8512ee10806f.png)

-- https://scrutinizer-ci.com/g/beyondcode/helo-laravel/inspections/434e509d-e069-426e-ae36-242d54f15aef

Not sure what this means

2021-01-06 11:27 UTC, dacoto97 requested changes
Add php 7.3 & 8.0

2021-01-06 11:27 UTC, dacoto97 commented on composer.json
> +        "php": ">=7.3",
"php": "^7.3|^8.0",

2021-03-05 03:34 UTC, devingray commented
Hi @mpociot @repat 

This PR is old now and I would like to make PR for this to get PHP 8 working :) Would you like a new PR or to update here?

2021-03-30 08:58 UTC, closed without merging